[package]
name = "rust_email_newsletter"
version = "0.1.0"
authors = ["Mike-Mp <mikemp@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
